name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag python-poetry-devcontainer

      - name: Log into registry
        run: echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io -u sthorsten --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/sthorsten/python-poetry-devcontainer
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME_BACKEND $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
